---
apiVersion: v1
kind: Service
metadata:
  name: web-volumes
spec:
  sessionAffinity: None
  selector:
    app: web-volumes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-volumes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-volumes
  template:
    metadata:
      labels:
        app: web-volumes
    spec:
      containers:
      - name: web
        image: nginx:1.17.8-alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
      volumes:
        - name: data
          hostPath:
            path: /host-volumes/nginx-data

