#
# Alternative way to run the database container (without docker-compose):
#    docker run  -e MYSQL_ROOT_PASSWORD=somewordpress -e MYSQL_DATABASE=wordpress -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=wordpress -v db_data:/var/lib/mysql -p 3306:3306 mysql:5.7
# you can connect to the database with this command: docker-compose exec db mysql -u wordpress -p wordpress -D wordpress
#
# show tables;

---
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   #wordpress:
     #image: wordpress:latest
     #ports:
       #- "8000:80"
     #environment:
       #WORDPRESS_DB_HOST: db:3306
       #WORDPRESS_DB_USER: wordpress
       #WORDPRESS_DB_PASSWORD: wordpress
       #WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
