# Test the deployment with:
# kubectl run -it --rm --image alpine/curl testbox -- ash
# curl web-service
#
# or with:
# kubectl get --raw /api/v1/namespaces/default/services/web-service/proxy/


---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  sessionAffinity: None
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
